development:
  stripe_publishable_key: pk_test_TTGqUXCMF8cEQehdmw643QA7
  stripe_secret_key: sk_test_eZTNWtbmz4CEr7wTQ4waGPsd
  S3_ACCESS_KEY: AKIAIKUOQ7IASY5ZY2IQ
  S3_SECRET_KEY: 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
